@startuml Website-Container-Diagram
!include <c4/C4_Context.puml>
!include <c4/C4_Container.puml>
title Website Container Diagram

Person_Ext(public_user, "Public User", "An unauthenticated user")
Person_Ext(collaborator_user, "Collaborator User", "An authorized and authenticated user")
Person_Ext(admin_user, "Admin User", "An authorized and authenticated user")
System_Ext(api, "API", "The API that the website uses to get data, can also be accessed by authorized 3rd parties.")

System_Boundary(spa, "SPA", "The React SPA") {
    Container(public_pages, "Public Pages", "Pages designed for unathenticated users")
    Container(collaborator_pages, "Collaborator Pages", "Pages designed for collaborators")
    Container(admin_pages, "Public Pages", "Pages designed for admins")
}

Rel(public_user, public_pages, "Uses")
Rel(collaborator_user, collaborator_pages, "Uses")
Rel(admin_user, admin_pages, "Uses")

Rel(public_pages, api, "Requests")
Rel(collaborator_pages, api, "Requests")
Rel(admin_pages, api, "Requests")

@enduml
