"""
This sets up the user groups required for the application to function as expected
"""
# Generated by Django 5.1.6 on 2025-02-19 18:38

from django.db import migrations
from django.conf import settings

def apply_migration(apps, _):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name=u'admin'),
        Group(name=u'collaborator'),
    ])

def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            u'admin',
            u'admin',
        ]
    ).delete()

class Migration(migrations.Migration):
    """
    Migration for creating user groups
    """

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL)
    ]

    operations = [
        migrations.RunPython(apply_migration)
    ]
