# Generated by Django 5.1.6 on 2025-03-23 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CHIL', '0001_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField()),
                ('start_timestamp', models.CharField(max_length=255)),
                ('end_timestamp', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'campaign_table',
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('deployment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('start_timestamp', models.DateField()),
                ('end_timestamp', models.DateField()),
            ],
            options={
                'db_table': 'deployment_table',
            },
        ),
        migrations.CreateModel(
            name='DeploymentInstrument',
            fields=[
                ('deployment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('campaign_id', models.BigIntegerField()),
                ('instrument_id', models.BigIntegerField()),
                ('start_timestamp', models.DateField()),
                ('end_timestamp', models.DateField()),
            ],
            options={
                'db_table': 'instrument_deployment_table',
            },
        ),
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('instrument_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instrument_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'instrument_type_table',
            },
        ),
    ]
