"""
This sets up the user groups required for the application to function as expected
"""
# Generated by Django 5.1.6 on 2025-02-19 18:38

from django.db import migrations

def apply_migration(apps, _):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name=u'admin'),
        Group(name=u'collaborator'),
    ])

class Migration(migrations.Migration):
    """
    Migration for creating user groups
    """
    dependencies = [
        ('CHIL', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(apply_migration)
    ]
