# Generated by Django 5.1.6 on 2025-03-31 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CHIL', '0001_user_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField()),
                ('start_timestamp', models.CharField(max_length=255)),
                ('end_timestamp', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'campaign_table',
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('deployment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('start_timestamp', models.DateField()),
                ('end_timestamp', models.DateField()),
            ],
            options={
                'db_table': 'deployment_table',
            },
        ),
        migrations.CreateModel(
            name='Ingest',
            fields=[
                ('ingest_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lingomo_id', models.TextField()),
                ('received_timestamp', models.DateTimeField()),
                ('imei', models.TextField()),
                ('serial', models.TextField()),
                ('momsn', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('accuracy', models.FloatField()),
            ],
            options={
                'db_table': 'ingest_lingomo_table',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('instrument_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('manufacture_date', models.DateField()),
                ('manufacture_batch', models.CharField(max_length=255)),
                ('commission_date', models.DateField()),
                ('notes', models.TextField()),
                ('pressure_keller_min', models.FloatField()),
                ('pressure_keller_max', models.FloatField()),
            ],
            options={
                'db_table': 'instrument_table',
            },
        ),
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('instrument_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instrument_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'instrument_type_table',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('process_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('level', models.IntegerField()),
                ('timestamp_begin', models.DateTimeField()),
                ('timestamp_end', models.DateTimeField()),
                ('notes', models.TextField()),
            ],
            options={
                'db_table': 'process_table',
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('receiver_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('imei_number', models.TextField(blank=True, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('manufacture_batch', models.TextField(blank=True, null=True)),
                ('commission_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'receiver_table',
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'newsletter_subscribers',
            },
        ),
        migrations.CreateModel(
            name='DeploymentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.deployment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deployment_access_table',
            },
        ),
        migrations.CreateModel(
            name='HydrobeanRaw',
            fields=[
                ('hydrobean_raw_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('receiver_data_id', models.IntegerField()),
                ('conductivity_raw', models.FloatField()),
                ('pressure_raw', models.IntegerField()),
                ('temperature_raw', models.IntegerField()),
                ('battery_voltage', models.IntegerField()),
                ('sequence_number', models.IntegerField()),
                ('rssi', models.FloatField()),
                ('packet_version', models.TextField()),
                ('ingest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.ingest')),
                ('instrument_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.instrument')),
            ],
            options={
                'db_table': 'hydrobean_raw_table',
            },
        ),
        migrations.CreateModel(
            name='DeploymentInstrument',
            fields=[
                ('deployment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('start_timestamp', models.DateField()),
                ('end_timestamp', models.DateField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.campaign')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.instrument')),
            ],
            options={
                'db_table': 'instrument_deployment_table',
            },
        ),
        migrations.CreateModel(
            name='CryowurstRaw',
            fields=[
                ('cryowurst_raw_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('receiver_data_id', models.IntegerField()),
                ('temperature_tmp117_raw', models.IntegerField()),
                ('mag_x_raw', models.IntegerField()),
                ('mag_y_raw', models.IntegerField()),
                ('mag_z_raw', models.IntegerField()),
                ('accel_imu_x_raw', models.IntegerField()),
                ('accel_imu_y_raw', models.IntegerField()),
                ('accel_imu_z_raw', models.IntegerField()),
                ('accel_tilt_x_raw', models.IntegerField()),
                ('accel_tilt_y_raw', models.IntegerField()),
                ('accel_tilt_z_raw', models.IntegerField()),
                ('pitch_raw', models.IntegerField()),
                ('roll_raw', models.IntegerField()),
                ('conductivity_raw', models.IntegerField()),
                ('pressure_raw', models.IntegerField()),
                ('temperature_keller_raw', models.IntegerField()),
                ('battery_voltage', models.IntegerField()),
                ('sequence_number', models.IntegerField()),
                ('rssi', models.FloatField()),
                ('packet_version', models.TextField()),
                ('ingest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.ingest')),
                ('instrument_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.instrument')),
            ],
            options={
                'db_table': 'cryowurst_raw_table',
            },
        ),
        migrations.CreateModel(
            name='CryoeggRaw',
            fields=[
                ('cryoegg_raw', models.BigAutoField(primary_key=True, serialize=False)),
                ('receiver_data_id', models.IntegerField()),
                ('conductivity_raw', models.IntegerField()),
                ('temperature_pt1000_raw', models.IntegerField()),
                ('pressure_raw', models.IntegerField()),
                ('temperature_raw', models.IntegerField()),
                ('battery_voltage', models.IntegerField()),
                ('sequence_number', models.FloatField()),
                ('rssi', models.FloatField()),
                ('packet_version', models.TextField()),
                ('ingest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.ingest')),
                ('instrument_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.instrument')),
            ],
            options={
                'db_table': 'cryoegg_raw_table',
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.instrumenttype'),
        ),
        migrations.CreateModel(
            name='HydrobeanData',
            fields=[
                ('hydrobean_data_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('conductivity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('temperature', models.FloatField()),
                ('hydrobean_raw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.hydrobeanraw')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.process')),
            ],
            options={
                'db_table': 'hydrobean_data_table',
            },
        ),
        migrations.CreateModel(
            name='CryowurstData',
            fields=[
                ('cryowurst_data_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('temperature_tmp117', models.FloatField(blank=True, null=True)),
                ('mag_x', models.FloatField(blank=True, null=True)),
                ('mag_y', models.FloatField(blank=True, null=True)),
                ('mag_z', models.FloatField(blank=True, null=True)),
                ('accel_imu_x', models.FloatField(blank=True, null=True)),
                ('accel_imu_y', models.FloatField(blank=True, null=True)),
                ('accel_imu_z', models.FloatField(blank=True, null=True)),
                ('accel_tilt_x', models.FloatField(blank=True, null=True)),
                ('accel_tilt_y', models.FloatField(blank=True, null=True)),
                ('accel_tilt_z', models.FloatField(blank=True, null=True)),
                ('pitch', models.FloatField(blank=True, null=True)),
                ('roll', models.FloatField(blank=True, null=True)),
                ('conductivity', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('temperature_keller', models.FloatField(blank=True, null=True)),
                ('cryowurst_raw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CHIL.cryowurstraw')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CHIL.process')),
            ],
            options={
                'db_table': 'cryowurst_data_table',
            },
        ),
        migrations.CreateModel(
            name='CryoeggData',
            fields=[
                ('cryoegg_data_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('conductivity', models.FloatField(blank=True, null=True)),
                ('temperature_pt1000', models.IntegerField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('receiver_voltage', models.FloatField(blank=True, null=True)),
                ('cryoegg_raw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CHIL.cryoeggraw')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CHIL.process')),
            ],
            options={
                'db_table': 'cryoegg_data_table',
            },
        ),
        migrations.CreateModel(
            name='ReceiverDeployment',
            fields=[
                ('receiver_deployment_id', models.AutoField(primary_key=True, serialize=False)),
                ('firmware_version', models.TextField(blank=True, null=True)),
                ('antenna_type', models.TextField(blank=True, null=True)),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField(blank=True, null=True)),
                ('service_timestamp', models.DateTimeField(blank=True, null=True)),
                ('original_latitude', models.FloatField(blank=True, null=True)),
                ('original_longitude', models.FloatField(blank=True, null=True)),
                ('original_elevation', models.FloatField(blank=True, null=True)),
                ('latest_latitude', models.FloatField(blank=True, null=True)),
                ('latest_longitude', models.FloatField(blank=True, null=True)),
                ('latest_elevation', models.FloatField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.campaign')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.deployment')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.receiver')),
            ],
            options={
                'db_table': 'receiver_deployments_table',
            },
        ),
    ]
