# Generated by Django 5.1.6 on 2025-03-22 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CHIL', '0001_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField()),
                ('start_timestamp', models.CharField(max_length=255)),
                ('end_timestamp', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'campaign_table',
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('deployment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('start_timestamp', models.DateField()),
                ('end_timestamp', models.DateField()),
            ],
            options={
                'db_table': 'deployment_table',
            },
        ),
        migrations.CreateModel(
            name='DeploymentInstrument',
            fields=[
                ('deployment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('campaign_id', models.BigIntegerField()),
                ('instrument_id', models.BigIntegerField()),
                ('start_timestamp', models.DateField()),
                ('end_timestamp', models.DateField()),
            ],
            options={
                'db_table': 'instrument_deployment_table',
            },
        ),
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('instrument_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instrument_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'instrument_type_table',
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'newsletter_subscribers',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('instrument_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('manufacture_date', models.DateField()),
                ('manufacture_batch', models.CharField(max_length=255)),
                ('commission_date', models.DateField()),
                ('notes', models.TextField()),
                ('pressure_keller_min', models.FloatField()),
                ('pressure_keller_max', models.FloatField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.instrumenttype')),
            ],
            options={
                'db_table': 'instrument_table',
            },
        ),
    ]
