# Generated by Django 5.1.6 on 2025-03-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHIL', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryowurstdata',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
