# Generated by Django 5.1.6 on 2025-03-25 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHIL', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentInstrument',
            fields=[
                ('deployment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('start_timestamp', models.DateField()),
                ('end_timestamp', models.DateField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.campaign')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.instrument')),
            ],
            options={
                'db_table': 'instrument_deployment_table',
            },
        ),
    ]
