# Generated by Django 5.1.6 on 2025-03-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHIL', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentInstrument',
            fields=[
                ('deployment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('campaign_id', models.BigIntegerField()),
                ('instrument_id', models.BigIntegerField()),
                ('start_timestamp', models.DateField()),
                ('end_timestamp', models.DateField()),
            ],
            options={
                'db_table': 'instrument_deployment_table',
            },
        ),
    ]
