# Generated by Django 5.1.6 on 2025-03-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHIL', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField()),
                ('start_timestamp', models.CharField(max_length=255)),
                ('end_timestamp', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'campaign_table',
            },
        ),
    ]
