# Generated by Django 5.1.6 on 2025-03-23 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHIL', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('receiver_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('imei_number', models.TextField(blank=True, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('manufacture_batch', models.TextField(blank=True, null=True)),
                ('commission_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'receiver_table',
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'newsletter_subscribers',
            },
        ),
        migrations.CreateModel(
            name='ReceiverDeployment',
            fields=[
                ('receiver_deployment_id', models.AutoField(primary_key=True, serialize=False)),
                ('firmware_version', models.TextField(blank=True, null=True)),
                ('antenna_type', models.TextField(blank=True, null=True)),
                ('start_timestamp', models.DateField()),
                ('end_timestamp', models.DateField(blank=True, null=True)),
                ('service_timestamp', models.DateField(blank=True, null=True)),
                ('original_latitude', models.FloatField(blank=True, null=True)),
                ('original_longitude', models.FloatField(blank=True, null=True)),
                ('original_elevation', models.FloatField(blank=True, null=True)),
                ('latest_latitude', models.FloatField(blank=True, null=True)),
                ('latest_longitude', models.FloatField(blank=True, null=True)),
                ('latest_elevation', models.FloatField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.campaign')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.deployment')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.receiver')),
            ],
            options={
                'db_table': 'receiver_deployments_table',
            },
        ),
    ]
