# Generated by Django 5.1.6 on 2025-03-24 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHIL', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingest',
            fields=[
                ('ingest_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lingomo_id', models.TextField()),
                ('received_timestamp', models.DateTimeField()),
                ('imei', models.TextField()),
                ('serial', models.TextField()),
                ('momsn', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('accuracy', models.FloatField()),
            ],
            options={
                'db_table': 'ingest_lingomo_table',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('process_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('level', models.IntegerField()),
                ('timestamp_begin', models.DateTimeField()),
                ('timestamp_end', models.DateTimeField()),
                ('notes', models.TextField()),
            ],
            options={
                'db_table': 'process_table',
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'newsletter_subscribers',
            },
        ),
        migrations.CreateModel(
            name='CryoeggRaw',
            fields=[
                ('cryoegg_raw_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('receiver_data_id', models.IntegerField()),
                ('conductivity_raw', models.IntegerField()),
                ('temperature_pt1000_raw', models.IntegerField()),
                ('pressure_raw', models.IntegerField()),
                ('temperature_raw', models.IntegerField()),
                ('battery_voltage', models.IntegerField()),
                ('sequence_number', models.FloatField()),
                ('rssi', models.FloatField()),
                ('packet_version', models.TextField()),
                ('instrument_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.instrument')),
                ('ingest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.ingest')),
            ],
            options={
                'db_table': 'cryoegg_raw_table',
            },
        ),
        migrations.CreateModel(
            name='CryowurstRaw',
            fields=[
                ('cryowurst_raw_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('receiver_data_id', models.IntegerField()),
                ('temperature_tmp117_raw', models.IntegerField()),
                ('mag_x_raw', models.IntegerField()),
                ('mag_y_raw', models.IntegerField()),
                ('mag_z_raw', models.IntegerField()),
                ('accel_imu_x_raw', models.IntegerField()),
                ('accel_imu_y_raw', models.IntegerField()),
                ('accel_imu_z_raw', models.IntegerField()),
                ('accel_tilt_x_raw', models.IntegerField()),
                ('accel_tilt_y_raw', models.IntegerField()),
                ('accel_tilt_z_raw', models.IntegerField()),
                ('pitch_raw', models.IntegerField()),
                ('roll_raw', models.IntegerField()),
                ('conductivity_raw', models.IntegerField()),
                ('pressure_raw', models.IntegerField()),
                ('temperature_keller_raw', models.IntegerField()),
                ('battery_voltage', models.IntegerField()),
                ('sequence_number', models.IntegerField()),
                ('rssi', models.FloatField()),
                ('packet_version', models.TextField()),
                ('instrument_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.instrument')),
                ('ingest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.ingest')),
            ],
            options={
                'db_table': 'cryowurst_raw_table',
            },
        ),
        migrations.CreateModel(
            name='HydrobeanRaw',
            fields=[
                ('hydrobean_raw_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('receiver_data_id', models.IntegerField()),
                ('conductivity_raw', models.FloatField()),
                ('pressure_raw', models.IntegerField()),
                ('temperature_raw', models.IntegerField()),
                ('battery_voltage', models.IntegerField()),
                ('sequence_number', models.IntegerField()),
                ('rssi', models.FloatField()),
                ('packet_version', models.TextField()),
                ('instrument_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.instrument')),
                ('ingest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.ingest')),
            ],
            options={
                'db_table': 'hydrobean_raw_table',
            },
        ),
        migrations.CreateModel(
            name='HydrobeanData',
            fields=[
                ('hydrobean_data_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('conductivity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('temperature', models.FloatField()),
                ('hydrobean_raw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.hydrobeanraw')),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.process')),
            ],
            options={
                'db_table': 'hydrobean_data_table',
            },
        ),
        migrations.CreateModel(
            name='CryowurstData',
            fields=[
                ('cryowurst_data_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('temperature_tmp117', models.FloatField()),
                ('mag_x', models.FloatField()),
                ('mag_y', models.FloatField()),
                ('mag_z', models.FloatField()),
                ('accel_imu_x', models.FloatField()),
                ('accel_imu_y', models.FloatField()),
                ('accel_imu_z', models.FloatField()),
                ('accel_tilt_x', models.FloatField()),
                ('accel_tilt_y', models.FloatField()),
                ('accel_tilt_z', models.FloatField()),
                ('pitch', models.FloatField()),
                ('roll', models.FloatField()),
                ('conductivity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('temperature_keller', models.FloatField()),
                ('cryowurst_raw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.cryowurstraw')),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.process')),
            ],
            options={
                'db_table': 'cryowurst_data_table',
            },
        ),
        migrations.CreateModel(
            name='CryoeggData',
            fields=[
                ('cryoegg_data_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('conductivity', models.FloatField()),
                ('temperature_pt1000', models.IntegerField()),
                ('pressure', models.FloatField()),
                ('temperature', models.FloatField()),
                ('cryoegg_raw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.cryoeggraw')),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.process')),
            ],
            options={
                'db_table': 'cryoegg_data_table',
            },
        ),
    ]
