# Generated by Django 5.1.6 on 2025-03-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHIL', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryoeggdata',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryowurstdata',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hydrobeanraw',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
