# Generated by Django 5.1.6 on 2025-03-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHIL', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryoeggGraph',
            fields=[
                ('cryoegg_graph_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url_id', models.CharField(blank=True, max_length=100, null=True)),
                ('graph_name', models.TextField(blank=True, null=True)),
                ('measurement', models.CharField(help_text='Measurement type', max_length=100)),
                ('start_date', models.DateTimeField(help_text='Start date of the measurement')),
                ('end_date', models.DateTimeField(help_text='End date of the measurement')),
                ('stroke', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'db_table': 'cryoegg_graph_data_table',
            },
        ),
    ]
