# Generated by Django 5.1.6 on 2025-03-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CHIL', '0003_deploymentaccess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deploymentaccess',
            old_name='user_id',
            new_name='username',
        ),
    ]
