# Generated by Django 5.1.6 on 2025-03-23 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHIL', '0003_receiver_subscribers_instrument_deploymentinstrument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('instrument_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('manufacture_date', models.DateField()),
                ('manufacture_batch', models.CharField(max_length=255)),
                ('commission_date', models.DateField()),
                ('notes', models.TextField()),
                ('pressure_keller_min', models.FloatField()),
                ('pressure_keller_max', models.FloatField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.instrumenttype')),
            ],
            options={
                'db_table': 'instrument_table',
            },
        ),
        migrations.CreateModel(
            name='DeploymentInstrument',
            fields=[
                ('deployment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('start_timestamp', models.DateField()),
                ('end_timestamp', models.DateField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.campaign')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHIL.instrument')),
            ],
            options={
                'db_table': 'instrument_deployment_table',
            },
        ),
    ]
