# Generated by Django 5.1.6 on 2025-03-24 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHIL', '0003_ingest_process_subscribers_cryoeggraw_cryowurstraw_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryoeggraw',
            old_name='cryoegg_raw_id',
            new_name='cryoegg_raw',
        ),
        migrations.RenameField(
            model_name='cryoeggraw',
            old_name='ingest_id',
            new_name='ingest',
        ),
        migrations.RemoveField(
            model_name='cryoeggdata',
            name='cryoegg_raw_id',
        ),
        migrations.RemoveField(
            model_name='cryowurstdata',
            name='cryowurst_raw_id',
        ),
        migrations.RemoveField(
            model_name='cryowurstdata',
            name='process_id',
        ),
        migrations.AddField(
            model_name='cryoeggdata',
            name='cryoegg_raw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CHIL.cryoeggraw'),
        ),
        migrations.AddField(
            model_name='cryowurstdata',
            name='cryowurst_raw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CHIL.cryowurstraw'),
        ),
        migrations.AddField(
            model_name='cryowurstdata',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CHIL.process'),
        ),
        migrations.AlterField(
            model_name='cryoeggdata',
            name='conductivity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cryoeggdata',
            name='pressure',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cryoeggdata',
            name='process_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CHIL.process'),
        ),
        migrations.AlterField(
            model_name='cryoeggdata',
            name='temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cryoeggdata',
            name='temperature_pt1000',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='accel_imu_x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='accel_imu_y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='accel_imu_z',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='accel_tilt_x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='accel_tilt_y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='accel_tilt_z',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='conductivity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='mag_x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='mag_y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='mag_z',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='pitch',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='pressure',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='roll',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='temperature_keller',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='temperature_tmp117',
            field=models.FloatField(null=True),
        ),
    ]
