# Generated by Django 5.1.6 on 2025-03-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHIL', '0004_cryowurstgraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryowurstdata',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
