# Generated by Django 5.1.6 on 2025-03-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CHIL', '0004_rename_user_id_deploymentaccess_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deploymentaccess',
            old_name='username',
            new_name='user_id',
        ),
    ]
