# Generated by Django 5.1.6 on 2025-03-24 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHIL', '0004_rename_cryoegg_raw_id_cryoeggraw_cryoegg_raw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryoeggdata',
            name='conductivity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryoeggdata',
            name='cryoegg_raw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CHIL.cryoeggraw'),
        ),
        migrations.AlterField(
            model_name='cryoeggdata',
            name='pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryoeggdata',
            name='process_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CHIL.process'),
        ),
        migrations.AlterField(
            model_name='cryoeggdata',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryoeggdata',
            name='temperature_pt1000',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='accel_imu_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='accel_imu_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='accel_imu_z',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='accel_tilt_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='accel_tilt_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='accel_tilt_z',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='conductivity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='cryowurst_raw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CHIL.cryowurstraw'),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='mag_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='mag_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='mag_z',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='pitch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CHIL.process'),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='roll',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='temperature_keller',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryowurstdata',
            name='temperature_tmp117',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
