# Generated by Django 5.1.6 on 2025-03-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CHIL', '0005_alter_cryoeggdata_conductivity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryoeggdata',
            old_name='process_id',
            new_name='process',
        ),
        migrations.RenameField(
            model_name='hydrobeandata',
            old_name='process_id',
            new_name='process',
        ),
    ]
