# Generated by Django 5.1.6 on 2025-03-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHIL', '0005_cryowurstdata_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryowurstgraph',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
