# Generated by Django 5.1.6 on 2025-03-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHIL', '0005_rename_username_deploymentaccess_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryowurstdata',
            name='UID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
