# Generated by Django 5.1.6 on 2025-03-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHIL', '0006_rename_process_id_cryoeggdata_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryoeggdata',
            name='receiver_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
