# Generated by Django 5.1.6 on 2025-04-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CHIL', '0006_cryowurstdata_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryowurstdata',
            old_name='UID',
            new_name='uid',
        ),
    ]
