stages:
  - lint
  - test
  - deploy

# frontend-lint:
#   stage: lint
#   image: node

#   script:
#       - cd frontend/CHIL
#       - node -v
#       - npm install
#       - npm run lint

# backend-lint:
#   stage: lint
#   image: python

#   script:
#     - cd backend/CHIL
#     - pip install Poetry
#     - poetry -V
#     - poetry install
#     - poetry run pylint ./chil


# frontend-test:
#   stage: test
#   image: node

#   script:
#     - cd frontend/CHIL
#     - node -v
#     - npm install
#     - npm run test

backend-test:
  stage: test
  image: python
  services:
    - name: mariadb:latest

  variables:
    # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
    MARIADB_DATABASE: $DB_NAME
    MARIADB_ROOT_PASSWORD: $DB_PASSWORD

  before_script:
    - apt-get update
    - apt-get install -y mariadb-client
    - apt-get install -y mariadb-server
    - mariadb --version
    - mariadb -u root -p --host=localhost
    - "$MARIADB_ROOT_PASSWORD"

  script:
    - cd backend/CHIL
    - pip install Poetry
    - poetry -V
    - poetry install
    - poetry run python manage.py test chil/tests --settings=config.django.test
    - CREATE DATABASE '$MARIADB_DATABASE';
    - USE '$MARIADB_DATABASE';
    - SOURCE ./backend/CHIL/schema/init-schema.sql;
    - SOURCE ./backend/CHIL/schema/init-metadata.sql;

pages:
  stage: deploy
  image: node:lts

  script:
    - mkdir public
    - npm install @redocly/cli
    - npx redocly build-docs -o public/index.html docs/api/openapi.yaml

  artifacts:
    paths:
      - public

  only:
    - master
