stages:
  - lint
  - test

frontend-lint:
  stage: lint
  image: node

  script:
      - cd frontend/CHIL
      - node -v
      - npm install
      - npm run lint

backend-lint:
  stage: lint
  image: python

  script:
    - cd backend/CHIL
    - pip install Poetry
    - poetry -V
    - poetry install
    - poetry run pylint ./chil