openapi: 3.0.3
info:
  title: Cardiff University CHIL
  description: |-
    This API is used for interacting with Cardiff University's CHIL project.
  version: 1.0.0

tags:
  - name: instrument
    description: Everything relating the instruments
  - name: receiver
    description: Everything relating to the recivers

paths:
  /instrument/{type}/list:
    get:
      tags:
        - instrument
      summary: Lists all instruments of a specified type
      description: Lists all instruments of a specified type
      operationId: getInstruments
      parameters:
        - name: type
          in: path
          description: 'The type of instrument to list'
          required: true
          schema:
            type: string
            enum: [
                'cryoegg',
                'cryowurst',
                'receiver'
              ]
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/instrument-list'
        '400':
          description: Type not found

  /receiver/list:
    get:
      tags:
        - receiver
      summary: Lists all of the recievers
      description: Lists all of the recievers
      operationId: getRecievers
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/receiver-list'

components:
  schemas:
    instrument-list:
      type: object
      properties:
        instrument_id:
          type: integer
          format: int10
          example: 1111111111
        type:
          type: string
          example: cryoegg
        manufacture_date:
          type: string
          example: 1970-00-00 00:00:00
        manufacture_batch:
          type: string
          example: CE1970
        commission_date:
          type: string
          example: 1970-00-00 00:00:00
        notes:
          type: string
          nullable: true
          example: Info about this specific instrument
        pressure_keller_min:
          type: number
          format: double
          example: 0.0
        pressure_keller_max:
          type: number
          format: double
          example: 100
    receiver-list:
      type: object
      properties:
        reciever_id:
          type: integer
          format: int10
          example: 10
        name:
          type: string
          example: Portable Reciever
        type:
          type: string
          example: tripod
          enum: [
            'tripod',
            'portable'
          ]
        imei_number:
          type: string
          nullable: true
          example: 111111111111111
        manufacture_date:
          type: string
          example: 1970-00-00 00:00:00
        manufacture_batch:
          type: string
          example: JJ_1970
        commission_date:
          type: string
          example: 1970-00-00 00:00:00
        notes:
          type: string
          nullable: true
          example: Info about this specific receiver