openapi: 3.0.3
info:
  title: Cardiff University CHIL
  description: |-
    This API is used for interacting with Cardiff University's CHIL project.
  version: 1.0.0

tags:
  - name: instrument
    description: Everything relating the instruments
  - name: receiver
    description: Everything relating to the recivers
  - name: data
    description: Get raw and processed data from all equipment types
  - name: campaign
    description: Everything relating to campaigns (Grouped deployments)
  - name: ingest
    description: Used by equipment to add data to the database

paths:
  /instrument/{type}:
    post:
      tags:
        - instrument
      summary: Create a new instrument of a specified type
      description: Create a new instrument of a specified type
      operationId: createInstrument
      security:
        - BearerAuth: []
      parameters:
        - name: type
          in: path
          description: The type of instrument to list
          required: true
          schema:
            type: string
            enum: [
                'cryoegg',
                'cryowurst',
                'hydrobean',
              ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/instrument'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/instrument'

        204:
          description: Existing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/instrument'

        403:
          description: Forbidden

        404:
          description: Type not found

  /instrument/{type}/list:
    get:
      tags:
        - instrument
      summary: Lists all instruments of a specified type
      description: Lists all instruments of a specified type
      operationId: getAllInstruments
      parameters:
        - name: type
          in: path
          description: The type of instrument to list
          required: true
          schema:
            type: string
            enum: [
                'cryoegg',
                'cryowurst',
                'hydrobean',
              ]
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/instrument-list'
        400:
          description: Type not found

  /instrument/{type}/{id}:
    get:
      tags:
        - instrument
      summary: Get infomation of a specific instrument by id
      description: Get infomation of a specific instrument by id
      operationId: getInstrument
      parameters:
        - name: type
          in: path
          description: The type of instrument
          required: true
          schema:
            type: string
            enum: [
                'cryoegg',
                'cryowurst',
                'hydrobean',
              ]
        - name: id
          in: path
          description: The id of the instrument
          required: true
          schema:
            type: integer
            format: int10
            example: 1111111111
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/instrument'
        404:
          description: Type or Id not found
    put:
      tags:
        - instrument
      summary: Update instrument entry
      description: Update instrument entry
      operationId: updateInstrument
      security:
        - BearerAuth: []
      parameters:
        - name: type
          in: path
          description: The type of instrument
          required: true
          schema:
            type: string
            enum: [
                'cryoegg',
                'cryowurst',
                'hydrobean',
              ]
        - name: id
          in: path
          description: The id of the instrument
          required: true
          schema:
            type: integer
            format: int10
            example: 1111111111
      requestBody:
        description: Update an existing instrument in the database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/instrument'
      responses:
        200:
          description: Success
        400:
          description: Bad Request
        404:
          description: Type or Id not found
        409:
          description: Conflict

    delete:
      tags:
        - instrument
      summary: Delete the instrument entry
      description: Delete the instrument entry
      operationId: deleteInstrument
      security:
        - BearerAuth: []
      parameters:
        - name: type
          in: path
          description: The type of instrument
          required: true
          schema:
            type: string
            enum: [
                'cryoegg',
                'cryowurst',
                'hydrobean',
              ]
        - name: id
          in: path
          description: The id of the instrument
          required: true
          schema:
            type: integer
            format: int10
            example: 1111111111
      responses:
        204:
          description: No Content
        404:
          description: Type or Id not found

  /receiver/list:
    get:
      tags:
        - receiver
      summary: Lists all of the recievers
      description: Lists all of the recievers
      operationId: getRecievers
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/receiver-list'

components:
  securitySchemes:
      BearerAuth:
        type: http
        scheme: bearer

      EquipmentApiKeyAuth:
        type: apiKey
        in: header
        name: Equipment-API-Key

  schemas:
    instrument:
      type: object
      properties:
        instrument_id:
          type: integer
          format: int10
          example: 1111111111
        type:
          type: string
          example: cryoegg
        manufacture_date:
          type: string
          example: 1970-00-00 00:00:00
        manufacture_batch:
          type: string
          example: CE1970
        commission_date:
          type: string
          example: 1970-00-00 00:00:00
        notes:
          type: string
          nullable: true
          example: Info about this specific instrument
        pressure_keller_min:
          type: number
          format: double
          example: 0.0
        pressure_keller_max:
          type: number
          format: double
          example: 100

    instrument-list:
      type: array
      items:
        type: object
        oneOf:
          - $ref: '#/components/schemas/instrument'

    receiver:
      type: object
      properties:
        reciever_id:
          type: integer
          format: int10
          example: 10
        name:
          type: string
          example: Portable Reciever
        type:
          type: string
          example: tripod
          enum: [
            'tripod',
            'portable'
          ]
        imei_number:
          type: string
          nullable: true
          example: 111111111111111
        manufacture_date:
          type: string
          example: 1970-00-00 00:00:00
        manufacture_batch:
          type: string
          example: JJ_1970
        commission_date:
          type: string
          example: 1970-00-00 00:00:00
        notes:
          type: string
          nullable: true
          example: Info about this specific receiver

    receiver-list:
        type: array
        items:
          type: object
          oneOf:
            - $ref: '#/components/schemas/receiver'